nelmio_api_doc:
    documentation:
        info:
            title: Blog Honeytech API
            description: Blog Honeytech API
            version: 1.0.0
        servers:
            - url: http://localhost:2908
              description: Local server
        components:
            securitySchemes:
                {}
    areas:
        path_patterns:
            - ^/api(?!/doc$)
