services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /var/www/app
        volumes:
            - '.:/var/www/app'
            - './docker/mysql/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql'
        environment:
            - MYSQL_ROOT_PASSWORD=PassWordRoot10!
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=PassWord10!
        ports:
            - '2910:3306'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 3s
            retries: 10

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/app
        volumes:
            - '.:/var/www/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2908:80'
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        working_dir: /var/www/app
        volumes:
            - '.:/var/www/app'
        depends_on:
            mysql:
                condition: service_healthy
